export const dummyUsers = [
  {
    id: 1,
    name: "Alice Mathew",
    email: "alice.mathew@example.com",
    username: "alice123",
    role: "Admin",
    location: "Kollam",
    phone: "9876543210",
  },
  {
    id: 2,
    name: "Nidhin Raj",
    email: "nidhin.raj@example.com",
    username: "nidhin_legend",
    role: "User",
    location: "Kottayam",
    phone: "9865432109",
  },
  {
    id: 3,
    name: "Adithyan S",
    email: "adithyan.s@example.com",
    username: "adi_codes",
    role: "Moderator",
    location: "Ernakulam",
    phone: "9123456780",
  },
  {
    id: 4,
    name: "Peter Parker",
    email: "spidey.peter@example.com",
    username: "spidey",
    role: "User",
    location: "New York",
    phone: "9991234567",
  },
  {
    id: 5,
    name: "Otto Octavius",
    email: "otto.oct@example.com",
    username: "doc_otto",
    role: "Scientist",
    location: "Brooklyn",
    phone: "8887654321",
  },
]
